services:
    postgres:
        image: 'postgres:latest'
        environment:
            - 'POSTGRES_DB=bbmk'
            - 'POSTGRES_PASSWORD=secret'
            - 'POSTGRES_USER=myuser'
        ports:
            - '5432'
