apiVersion: v1
kind: List
items:
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
          name: openshift-app
      spec:
          replicas: 1
          selector:
              app: openshift-app
          strategy:
              type: Recreate
          template:
              metadata:
                  labels:
                      app: openshift-app
              spec:
                  containers:
                      - image: "docker-registry.default.svc:5000/openshift/openshift-app:latest"
                        name: openshift-app
                        ports:
                            - containerPort: 8080
                              protocol: TCP
          triggers:
              - type: ConfigChange
              - imageChangeParams:
                    automatic: true
                    containerNames:
                        - openshift-app
                    from:
                        kind: ImageStreamTag
                        name: openshift-app:latest
                type: ImageChange
    - apiVersion: v1
      kind: Service
      metadata:
          name: openshift-app
      spec:
          ports:
              - name: http
                port: 8080
                protocol: TCP
                targetPort: 8080
          selector:
              app: openshift-app
    - apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
          name: openshift-app
      spec:
          host: ""
          to:
              kind: Service
              name: openshift-app
